buildFib:
	gcc fib.c -o obj/fib

runFib:
	./obj/fib

buildFibInput:
	gcc fibInput.c -o obj/fibInput

runFibInput:
	./obj/fibInput

buildFibFun:
	gcc fibFunTest.c fibFun.c  -o obj/fibFun

runFibFun:
	./obj/fibFun
buildAvg:
	gcc avg.c -o obj/avg
runAvg:
	./obj/avg
